/* eslint-env node */
const cv = (name) => `var(${name})`;

module.exports = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        sage: {
          50:  cv('--color-sage-50'),
          100: cv('--color-sage-100'),
          300: cv('--color-sage-300'),
          500: cv('--color-sage-500'),
          700: cv('--color-sage-700'),
          900: cv('--color-sage-900'),
          DEFAULT: cv('--color-sage-700'),
        },
        cream: {
          50:  cv('--color-cream-50'),
          100: cv('--color-cream-100'),
          300: cv('--color-cream-300'),
          500: cv('--color-cream-500'),
          700: cv('--color-cream-700'),
          900: cv('--color-cream-900'),
          DEFAULT: cv('--color-cream-100'),
        },
        indigo: {
          50:  cv('--color-indigo-50'),
          100: cv('--color-indigo-100'),
          300: cv('--color-indigo-300'),
          500: cv('--color-indigo-500'),
          700: cv('--color-indigo-700'),
          900: cv('--color-indigo-900'),
          DEFAULT: cv('--color-indigo-500'),
        },
        amber: {
          50:  cv('--color-amber-50'),
          100: cv('--color-amber-100'),
          300: cv('--color-amber-300'),
          500: cv('--color-amber-500'),
          700: cv('--color-amber-700'),
          900: cv('--color-amber-900'),
          DEFAULT: cv('--color-amber-500'),
        },
        charcoal: {
          50:  cv('--color-charcoal-50'),
          100: cv('--color-charcoal-100'),
          300: cv('--color-charcoal-300'),
          500: cv('--color-charcoal-500'),
          700: cv('--color-charcoal-700'),
          900: cv('--color-charcoal-900'),
          DEFAULT: cv('--color-charcoal-900'),
        },
        crisis: {
          50:  cv('--color-crisis-50'),
          100: cv('--color-crisis-100'),
          500: cv('--color-crisis-500'),
          600: cv('--color-crisis-600'),
          700: cv('--color-crisis-700'),
          900: cv('--color-crisis-900'),
          DEFAULT: cv('--color-crisis-600'),
        },
        surface: {
          DEFAULT:  cv('--surface-base'),
          base:     cv('--surface-base'),
          elevated: cv('--surface-elevated'),
          muted:    cv('--surface-muted'),
          inverse:  cv('--surface-inverse'),
        },
        ink: {
          DEFAULT: cv('--text-default'),
          soft:    cv('--text-soft'),
          subtle:  cv('--text-subtle'),
        },
        border: {
          DEFAULT: cv('--border-default'),
          soft:    cv('--border-soft'),
          strong:  cv('--border-strong'),
        },
        primary: {
          50:  cv('--color-primary-50'),
          100: cv('--color-primary-100'),
          200: cv('--color-sage-100'),
          300: cv('--color-sage-300'),
          400: cv('--color-sage-300'),
          500: cv('--color-primary-500'),
          600: cv('--color-primary-600'),
          700: cv('--color-primary-700'),
          800: cv('--color-sage-700'),
          900: cv('--color-primary-900'),
          950: cv('--color-sage-900'),
        },
        accent: {
          50:  cv('--color-amber-50'),
          100: cv('--color-amber-100'),
          200: cv('--color-amber-100'),
          300: cv('--color-amber-300'),
          400: cv('--color-amber-300'),
          500: cv('--color-amber-500'),
          600: cv('--color-amber-700'),
          700: cv('--color-amber-700'),
          800: cv('--color-amber-900'),
          900: cv('--color-amber-900'),
          950: cv('--color-amber-900'),
        },
        success: {
          50:  cv('--color-success-50'),
          100: cv('--color-success-100'),
          200: cv('--color-sage-100'),
          300: cv('--color-sage-300'),
          400: cv('--color-sage-300'),
          500: cv('--color-success-500'),
          600: cv('--color-success-600'),
          700: cv('--color-success-700'),
          800: cv('--color-sage-700'),
          900: cv('--color-success-900'),
        },
        warning: {
          50:  cv('--color-warning-50'),
          100: cv('--color-warning-100'),
          200: cv('--color-amber-100'),
          300: cv('--color-amber-300'),
          400: cv('--color-amber-300'),
          500: cv('--color-warning-500'),
          600: cv('--color-warning-600'),
          700: cv('--color-warning-700'),
          800: cv('--color-amber-900'),
          900: cv('--color-warning-900'),
        },
        danger: {
          50:  cv('--color-danger-50'),
          100: cv('--color-danger-100'),
          200: cv('--color-crisis-100'),
          300: cv('--color-crisis-500'),
          400: cv('--color-crisis-500'),
          500: cv('--color-danger-500'),
          600: cv('--color-danger-600'),
          700: cv('--color-danger-700'),
          800: cv('--color-crisis-900'),
          900: cv('--color-danger-900'),
        },
        neutral: {
          50:  cv('--color-cream-50'),
          100: cv('--color-cream-100'),
          200: cv('--border-soft'),
          300: cv('--border-default'),
          400: cv('--text-subtle'),
          500: cv('--text-subtle'),
          600: cv('--text-soft'),
          700: cv('--color-charcoal-500'),
          800: cv('--color-charcoal-700'),
          900: cv('--color-charcoal-900'),
          950: cv('--color-charcoal-900'),
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'system-ui',
          'sans-serif',
        ],
      },
      fontSize: {
        'xs':   ['0.75rem',  { lineHeight: '1.05rem' }],
        'sm':   ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem',     { lineHeight: '1.55'    }],
        'lg':   ['1.125rem', { lineHeight: '1.6rem'  }],
        'xl':   ['1.25rem',  { lineHeight: '1.65rem' }],
        '2xl':  ['1.5rem',   { lineHeight: '1.85rem' }],
        '3xl':  ['1.875rem', { lineHeight: '2.15rem' }],
        '4xl':  ['2.25rem',  { lineHeight: '2.5rem'  }],
        '5xl':  ['3rem',     { lineHeight: '3.15rem' }],
        'micro':   ['0.6875rem', { lineHeight: '1rem',     letterSpacing: '0.04em' }],
        'caption': ['0.8125rem', { lineHeight: '1.15rem'  }],
        'body':    ['1rem',      { lineHeight: '1.55'     }],
        'h3':      ['1.125rem',  { lineHeight: '1.45',    fontWeight: '500' }],
        'h2':      ['1.5rem',    { lineHeight: '1.3',     fontWeight: '600' }],
        'h1':      ['2rem',      { lineHeight: '1.2',     fontWeight: '600', letterSpacing: '-0.01em' }],
        'display': ['3.25rem',   { lineHeight: '1.05',    fontWeight: '600', letterSpacing: '-0.02em' }],
      },
      fontWeight: {
        regular:  '400',
        medium:   '500',
        semibold: '600',
      },
      lineHeight: {
        body:  '1.55',
        snug:  '1.35',
        tight: '1.2',
      },
      spacing: {
        'card':              cv('--space-card'),
        'card-tight':        cv('--space-card-tight'),
        'section-y':         cv('--space-section-y-mobile'),
        'section-y-mobile':  cv('--space-section-y-mobile'),
        'section-y-desktop': cv('--space-section-y-desktop'),
      },
      borderRadius: {
        'sm':   cv('--radius-sm'),
        'md':   cv('--radius-md'),
        'lg':   cv('--radius-lg'),
        'xl':   cv('--radius-xl'),
        '2xl':  cv('--radius-2xl'),
        '3xl':  '1.5rem',
        'pill': cv('--radius-pill'),
      },
      boxShadow: {
        'soft':         cv('--shadow-soft'),
        'card':         cv('--shadow-card'),
        'card-hover':   cv('--shadow-medium'),
        'medium':       cv('--shadow-medium'),
        'strong':       cv('--shadow-strong'),
        'sm':           cv('--shadow-soft'),
        'DEFAULT':      cv('--shadow-card'),
        'md':           cv('--shadow-medium'),
        'lg':           cv('--shadow-medium'),
        'xl':           cv('--shadow-strong'),
        'premium-glow': '0 0 0 1px rgb(232 168 124 / 0.20), 0 4px 12px -2px rgb(232 168 124 / 0.20)',
      },
      animation: {
        'fade-in':    'fadeIn 0.3s ease-out',
        'slide-up':   'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-up':   'scaleUp 0.2s ease-out',
        'pulse-soft': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleUp: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-soft':   'linear-gradient(135deg, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
