/**
 * Original sample challenge data from the deprecated SocialChallenges
 * component. Preserved verbatim under [IA-6] so a future Communities
 * feature can use the same seed shape. Do NOT import from production.
 */
import type { Challenge } from './types';

export const ACTIVE_CHALLENGES: Challenge[] = [
  {
    id: 'dry-january-2024',
    title: 'Dry January Challenge',
    description: 'Join thousands in starting the year alcohol-free. Build healthy habits that last.',
    icon: '❄️',
    category: 'special',
    difficulty: 'medium',
    duration: '31 days',
    participants: 12847,
    completionRate: 73,
    rewards: { points: 500, badge: '🏔️', title: 'January Champion' },
    requirements: [
      { type: 'streak', target: 31, description: 'Stay alcohol-free for all 31 days of January' },
    ],
    startDate: new Date('2024-01-01').getTime(),
    endDate: new Date('2024-01-31').getTime(),
    joined: false,
    premium: false,
  },
  {
    id: 'weekend-warrior-feb',
    title: 'Weekend Warrior',
    description: 'Master your weekends - the ultimate test of willpower and social navigation.',
    icon: '🏋️',
    category: 'streak',
    difficulty: 'hard',
    duration: '4 weekends',
    participants: 3245,
    completionRate: 58,
    rewards: { points: 300, badge: '💪', title: 'Weekend Master' },
    requirements: [
      { type: 'streak', target: 4, description: 'Stay alcohol-free for 4 consecutive weekends' },
      { type: 'activity', target: 8, description: 'Log 8 alternative weekend activities' },
    ],
    joined: true,
    progress: 25,
    premium: false,
  },
  {
    id: 'mindful-march',
    title: 'Mindful March',
    description: 'Focus on mental wellness with daily check-ins and mindfulness practices.',
    icon: '🧘',
    category: 'mindfulness',
    difficulty: 'easy',
    duration: '31 days',
    participants: 8934,
    completionRate: 82,
    rewards: { points: 200, badge: '☮️', title: 'Zen Achiever' },
    requirements: [
      { type: 'mood', target: 31, description: 'Complete daily mood check-ins for all of March' },
      { type: 'activity', target: 15, description: 'Practice 15 mindfulness activities' },
    ],
    joined: false,
    premium: false,
  },
  {
    id: 'social-butterfly-sprint',
    title: 'Social Butterfly Sprint',
    description: 'Navigate 10 social situations while maintaining your alcohol-free commitment.',
    icon: '🦋',
    category: 'social',
    difficulty: 'medium',
    duration: '2 weeks',
    participants: 1876,
    completionRate: 67,
    rewards: { points: 150, badge: '🌟', title: 'Social Navigator' },
    requirements: [
      { type: 'activity', target: 10, description: 'Successfully handle 10 social drinking situations' },
      { type: 'limit', target: 0, description: 'Maintain zero alcohol consumption during social events' },
    ],
    joined: false,
    premium: true,
  },
  {
    id: 'health-metrics-challenge',
    title: 'Health Metrics Challenge',
    description: 'Track comprehensive health improvements over 30 days.',
    icon: '📈',
    category: 'health',
    difficulty: 'expert',
    duration: '30 days',
    participants: 567,
    completionRate: 45,
    rewards: { points: 400, badge: '🏥', title: 'Health Data Pro' },
    requirements: [
      { type: 'mood', target: 30, description: 'Log daily mood and energy levels' },
      { type: 'activity', target: 20, description: 'Track 20 health improvement metrics' },
    ],
    joined: false,
    premium: true,
  },
  {
    id: 'community-support-challenge',
    title: 'Community Support Challenge',
    description: 'Help and encourage others in their alcohol-free journey.',
    icon: '🤝',
    category: 'social',
    difficulty: 'medium',
    duration: '3 weeks',
    participants: 2341,
    completionRate: 71,
    rewards: { points: 250, badge: '❤️', title: 'Community Champion' },
    requirements: [
      { type: 'activity', target: 15, description: 'Provide support or encouragement to community members' },
      { type: 'streak', target: 21, description: 'Maintain your own alcohol-free streak' },
    ],
    joined: false,
    premium: true,
  },
];
