/**
 * Ensure .size-limit.cjs points to real built JS assets.
 *
 * [POLISH-SIZE-BUDGETS] Round-2 enforcement:
 *   - 100 KB eager-JS-gz   → initial bundle (index-*.js)
 *   - 130 KB total-init    → eager JS + CSS + HTML, gz
 *   - 250 KB largest-async → biggest single async chunk, gz
 *
 * The vendor + react chunks are eager too (referenced from index.html
 * <script> + <link rel="modulepreload">), so they count toward total
 * init alongside index-*.js.
 *
 * Async chunks are everything else under dist/assets/. The largest is
 * computed at config-write time so size-limit gets a single concrete
 * path; size-limit cannot do "max of N files" by itself.
 *
 * Bug fix: previous version used path.join for glob patterns. On
 * Windows that produces backslashes, which glob treats as escapes
 * → zero matches → silent fall-through to the placeholder config.
 * Glob now gets forward-slash patterns explicitly.
 */
import fs from "fs";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const { sync: globSync } = require("glob");

const EAGER_KB = parseInt(process.env.SIZE_LIMIT_EAGER_KB ?? "100", 10);
const TOTAL_KB = parseInt(process.env.SIZE_LIMIT_TOTAL_KB ?? "130", 10);
const ASYNC_KB = parseInt(process.env.SIZE_LIMIT_ASYNC_KB ?? "250", 10);

const CANDIDATES = [
  "dist",
  "build",
  "www",
  "packages/app/dist",
  "apps/alchohalt/dist",
  "frontend/dist",
];

function existsDir(p) {
  try { return fs.statSync(p).isDirectory(); } catch { return false; }
}

function pickOutDir() {
  for (const dir of CANDIDATES) {
    if (!existsDir(dir)) continue;
    if (globSync(`${dir}/assets/*.js`, { nodir: true }).length > 0) return dir;
    if (globSync(`${dir}/**/*.js`, { nodir: true }).length > 0) return dir;
  }
  return null;
}

const outDir = pickOutDir();
if (!outDir) {
  console.warn("[size-limit] No assets found. Writing placeholder config.");
  fs.writeFileSync(".size-limit.cjs", "module.exports=[{path:'package.json',limit:'1 KB'}];", "utf8");
  process.exit(0);
}

// 1) Initial JS chunk: dist/assets/index-*.js
// 2) Eager bundle: index-*.js + react-*.js + vendor-*.js + index-*.css + index.html
//    (whatever index.html actually references at boot)
// 3) Largest async chunk: max-by-size of dist/assets/*.js minus the eager set
const eagerJs = globSync(`${outDir}/assets/index-*.js`, { nodir: true });
const eagerCss = globSync(`${outDir}/assets/index-*.css`, { nodir: true });
const reactChunk = globSync(`${outDir}/assets/react-*.js`, { nodir: true });
const vendorChunk = globSync(`${outDir}/assets/vendor-*.js`, { nodir: true });
const allJs = globSync(`${outDir}/assets/*.js`, { nodir: true });
const eagerSet = new Set([...eagerJs, ...reactChunk, ...vendorChunk]);
const asyncJs = allJs.filter((p) => !eagerSet.has(p));

let largestAsyncPath = null;
let largestAsyncBytes = 0;
for (const p of asyncJs) {
  const sz = fs.statSync(p).size;
  if (sz > largestAsyncBytes) { largestAsyncBytes = sz; largestAsyncPath = p; }
}

const totalInit = [...eagerJs, ...reactChunk, ...vendorChunk, ...eagerCss, `${outDir}/index.html`]
  .filter((p) => fs.existsSync(p))
  .map((p) => p.replace(/\\/g, "/"));

const initialJsPattern = (eagerJs[0] ?? `${outDir}/assets/index-*.js`).replace(/\\/g, "/");
const largestAsyncPattern = largestAsyncPath
  ? largestAsyncPath.replace(/\\/g, "/")
  : `${outDir}/assets/*.js`;

const config = [
  {
    name: "Eager JS (gzip)",
    path: initialJsPattern,
    limit: `${EAGER_KB} KB`,
    gzip: true,
  },
  {
    name: "Total initial bundle (eager JS + CSS + HTML, gzip)",
    path: totalInit,
    limit: `${TOTAL_KB} KB`,
    gzip: true,
  },
  {
    name: "Largest async chunk (gzip)",
    path: largestAsyncPattern,
    limit: `${ASYNC_KB} KB`,
    gzip: true,
  },
];

const cfgFile = `// Auto-generated by tools/ensure_size_limit_config.js
// Edit budgets via env: SIZE_LIMIT_EAGER_KB / SIZE_LIMIT_TOTAL_KB / SIZE_LIMIT_ASYNC_KB
module.exports = ${JSON.stringify(config, null, 2)};
`;
fs.writeFileSync(".size-limit.cjs", cfgFile, "utf8");
console.log(`[size-limit] Wrote 3 budgets for outDir: ${outDir}`);
console.log(`  Eager JS:       ${EAGER_KB} KB gz   (${initialJsPattern})`);
console.log(`  Total init:     ${TOTAL_KB} KB gz   (${totalInit.length} files)`);
console.log(`  Largest async:  ${ASYNC_KB} KB gz   (${largestAsyncPattern}, ${(largestAsyncBytes / 1024).toFixed(1)} KB raw)`);
